### ISSUE TITLE
2.2.0: Problem with running test suite

### ISSUE THREAD

**Issue by kloczek** [storaged-project/blivet-gui#234]
```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/blivet-gui-2.2.0-2.fc34.x86_64/usr/lib/python3.8/site-packages
+ xvfb-run -s '-screen 0 640x480x8 -extension RANDR' /usr/bin/python3 tests/run_tests.py blivetgui_tests
Failed to add test 'unittest.loader._FailedTest.blivetgui_tests.add_dialog_test' to test suite.
```
```
[tkloczko@barrel SPECS]$ ls -lr /home/tkloczko/rpmbuild/BUILDROOT/blivet-gui-2.2.0-2.fc34.x86_64/usr/lib/python3.8/site-packages
total 4
-rw-r--r--. 1 tkloczko tkloczko 269 Sep 11 16:31 blivet_gui-2.2.0-py3.8.egg-info
drwxr-xr-x. 1 tkloczko tkloczko 588 Sep 11 16:31 blivetgui
```

**Comment by vojtechtrefny** [comment]
Wow, less than 15 minutes after the release, that was fast :-)

Can you try to run the failed test manually? It should print more information about why loading the test failed.

`PYTHONPATH=. python3 tests/blivetgui_tests/add_dialog_test.py`

**Comment by kloczek** [comment]
Executed in source tree:
```
[tkloczko@barrel blivet-gui-2.2.0]$ PYTHONPATH=. python3 tests/blivetgui_tests/add_dialog_test.py
Traceback (most recent call last):
  File "tests/blivetgui_tests/add_dialog_test.py", line 6, in <module>
    from blivetgui.dialogs.add_dialog import AdvancedOptions, AddDialog
  File "/home/tkloczko/rpmbuild/BUILD/blivet-gui-2.2.0/blivetgui/dialogs/add_dialog.py", line 33, in <module>
    from blivet import size
ModuleNotFoundError: No module named 'blivet'
```
I've been tryig to change in rpm spec file in `%check` (for whole test suite) to use current directory and of course it fails as well
```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/blivet-gui-2.2.0
+ xvfb-run -s '-screen 0 640x480x8 -extension RANDR' /usr/bin/python3 tests/run_tests.py blivetgui_tests
Failed to add test 'unittest.loader._FailedTest.blivetgui_tests.add_dialog_test' to test suite.
```

**Comment by vojtechtrefny** [comment]
> `ModuleNotFoundError: No module named 'blivet'`

You are missing some dependencies. You probably shouldn't run tests during build -- there is quite a few dependencies for both `make test` and `make check` -- but if you really want to, you'll need to add all runtime dependencies as `BuildRequires` plus some extra test dependencies like `mock` (see [install-test-dependencies.yml](https://github.com/storaged-project/blivet-gui/blob/master/install-test-dependencies.yml) for details).

**Comment by kloczek** [comment]
Looks like 2.2.1 is OK now.
Closing.

Thx
```
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/blivet-gui-2.2.1:/home/tkloczko/rpmbuild/BUILDROOT/blivet-gui-2.2.1-2.fc34.x86_64/usr/lib/python3.8/site-packages
+ xvfb-run -s '-screen 0 640x480x8 -extension RANDR' /usr/bin/python3 tests/run_tests.py blivetgui_tests
test_allowed_device_types (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_btrfs_parents (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_btrfs_selection (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_btrfsvolume_widgets (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_fs_chooser (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_fs_chooser_biosboot (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_label_validity_check (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_lvm_parents (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_lvm_selection (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_lvm_widgets (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_lvmlv_parents (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_md_selection (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_md_type (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_mdraid_widgets (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_mountpoint_validity_check (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_name_validity_check (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_parents_max_size_limit (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_parents_selection (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_parents_update (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_partition_parents (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_partition_selection (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_partition_widgets (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_raid_type (blivetgui_tests.add_dialog_test.AddDialogTest) ... ok
test_allowed_pesize (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_extended_partition (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_gpt_partitions (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_logical_partition (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_lvm_options (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_mdraid_options (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_mdraid_validation (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_normal_partition (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_partition_options (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_selection (blivetgui_tests.add_dialog_test.AdvancedOptionsTest) ... ok
test_convert_answer (blivetgui_tests.client_test.BlivetGUIClientTest) ... ok
test_convert_args (blivetgui_tests.client_test.BlivetGUIClientTest) ... ok
test_basic (blivetgui_tests.edit_dialog_test.FormatDialogTest) ... ok
test_installer (blivetgui_tests.edit_dialog_test.FormatDialogTest) ... ok
test_append (blivetgui_tests.list_actions_test.ListActionsTest) ... ok
test_clear (blivetgui_tests.list_actions_test.ListActionsTest) ... ok
test_initial_state (blivetgui_tests.list_actions_test.ListActionsTest) ... ok
test_pop (blivetgui_tests.list_actions_test.ListActionsTest) ... ok
test_add_to_store (blivetgui_tests.list_partitions_test.ListPartitionsTest) ... ok
test_allow_add (blivetgui_tests.list_partitions_test.ListPartitionsTest) ... ok
test_allow_delete (blivetgui_tests.list_partitions_test.ListPartitionsTest) ... ok
test_proxy_data_container (blivetgui_tests.proxy_test.ProxyUtilsTest) ... ok
test_proxy_id (blivetgui_tests.proxy_test.ProxyUtilsTest) ... ok
test_getattr (blivetgui_tests.server_test.BlivetProxyObjectTest) ... ok
test_getitem (blivetgui_tests.server_test.BlivetProxyObjectTest) ... ok
test_len (blivetgui_tests.server_test.BlivetProxyObjectTest) ... ok
test_setattr (blivetgui_tests.server_test.BlivetProxyObjectTest) ... ok
test_str (blivetgui_tests.server_test.BlivetProxyObjectTest) ... ok
test_convert_args (blivetgui_tests.server_test.BlivetUtilsServerTest) ... ok
test_convert_kwargs (blivetgui_tests.server_test.BlivetUtilsServerTest) ... ok
test_pickle_answer (blivetgui_tests.server_test.BlivetUtilsServerTest) ... ok
test_10_basic (blivetgui_tests.size_widgets_test.ParentAreaTest)
Test basic ParentArea functionality ... ok
test_20_parent_selection (blivetgui_tests.size_widgets_test.ParentAreaTest)
Test ParentArea functionality when (de)selecting some parents ... ok
test_30_size_selection (blivetgui_tests.size_widgets_test.ParentAreaTest)
Test ParentArea functionality when changing size of some parents ... ok
test_40_main_update (blivetgui_tests.size_widgets_test.ParentAreaTest)
Test updating values of main chooser in SizeArea ... ok
test_50_selected (blivetgui_tests.size_widgets_test.ParentAreaTest)
Test if widget returns what user selected ... ok
test_10_basic (blivetgui_tests.size_widgets_test.ParentChooserTest)
Test basic ParentChooser functionality ... ok
test_20_selection (blivetgui_tests.size_widgets_test.ParentChooserTest)
Test (de)selecting parent ... ok
test_30_size_selection (blivetgui_tests.size_widgets_test.ParentChooserTest)
Test chaning size selection ... ok
test_40_limits (blivetgui_tests.size_widgets_test.ParentChooserTest)
Test setting limits (min/max size) ... ok
test_50_signals (blivetgui_tests.size_widgets_test.ParentChooserTest)
Test connecting signals and signal handling ... ok
test_10_basic (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test basic SizeArea functionality ... ok
test_20_advanced_allowed (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea functionality with ParentArea allowed ... ok
test_30_advanced_enforced (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea functionality with ParentArea enforced ... ok
test_40_basic_limits (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea limits functionality without ParentArea ... ok
test_45_basic_limits_combined (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea limits functionality without ParentArea ... ok
test_50_advanced_limits (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea limits functionality with ParentArea ... ok
test_50_advanced_limits_raid (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea limits functionality with ParentArea with RAID ... ok
test_60_reserved_size (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea reserved size functionality without ParentArea ... ok
test_60_reserved_size_advanced (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test SizeArea reserved size functionality with ParentArea ... ok
test_70_parent_allocation (blivetgui_tests.size_widgets_test.SizeAreaTest)
Test allocating size on parents without ParentArea ... ok
test_10_unit_change (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_20_scale_spin (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_30_get_size (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_40_set_size (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_50_set_limits (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_60_widget_status (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_70_signals (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_80_selection (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_90_available_units (blivetgui_tests.size_widgets_test.SizeChooserAreaTest) ... ok
test_resizable (blivetgui_tests.utils_test.BlivetUtilsTest) ... ok
test_free_basic (blivetgui_tests.utils_test.FreeSpaceDeviceTest) ... ok
test_free_disk (blivetgui_tests.utils_test.FreeSpaceDeviceTest) ... ok
test_free_protected (blivetgui_tests.utils_test.FreeSpaceDeviceTest) ... ok
test_free_type (blivetgui_tests.utils_test.FreeSpaceDeviceTest) ... ok
test_encrypt_validity_check (blivetgui_tests.widgets_test.EncryptionChooserTest) ... ok
test_encryption_chooser (blivetgui_tests.widgets_test.EncryptionChooserTest) ... ok
test_encryption_selection (blivetgui_tests.widgets_test.EncryptionChooserTest) ... ok
test_passphrase_entry (blivetgui_tests.widgets_test.EncryptionChooserTest) ... ok
test_10_update (blivetgui_tests.widgets_test.RaidChooserTest) ... ok
test_20_selection (blivetgui_tests.widgets_test.RaidChooserTest) ... ok

----------------------------------------------------------------------
Ran 94 tests in 2.438s
```
