### ISSUE TITLE
unable to launch on ubuntu 20.04 (obs)

### ISSUE THREAD

**Issue by buck2202** [storaged-project/blivet-gui#290]
I've installed `blivet-gui` from OBS on a very fresh install of linux mint 20 (ubuntu 20.04 base). Trying to launch from the system menu fails silently; launching from a terminal, I get this
```
$ sudo blivet-gui
Traceback (most recent call last):
  File "/usr/bin/blivet-gui", line 40, in <module>
    from blivetgui.dialogs.message_dialogs import ErrorDialog
  File "/usr/lib/python3/dist-packages/blivetgui/dialogs/message_dialogs.py", line 31, in <module>
    from .helpers import adjust_scrolled_size
  File "/usr/lib/python3/dist-packages/blivetgui/dialogs/helpers.py", line 34, in <module>
    from blivet import devicefactory
  File "/usr/lib/python3/dist-packages/blivet/devicefactory.py", line 27, in <module>
    from .devices import BTRFSDevice, DiskDevice
  File "/usr/lib/python3/dist-packages/blivet/devices/__init__.py", line 24, in <module>
    from .storage import StorageDevice
  File "/usr/lib/python3/dist-packages/blivet/devices/storage.py", line 33, in <module>
    from ..formats import get_format, DeviceFormat
  File "/usr/lib/python3/dist-packages/blivet/formats/__init__.py", line 46, in <module>
    from ..tasks import fsinfo
  File "/usr/lib/python3/dist-packages/blivet/tasks/fsinfo.py", line 29, in <module>
    from . import availability
  File "/usr/lib/python3/dist-packages/blivet/tasks/availability.py", line 377, in <module>
    technologies={blockdev.LVMTech.VDO: (blockdev.LVMTechMode.CREATE |
AttributeError: type object 'LVMTech' has no attribute 'VDO'
```

The trace seems to suggest that I should've gotten an error message--does this suggest a dependency issue, and/or should the `AttributeError` have been fatal?

**Comment by vojtechtrefny** [comment]
The problem is too old version of libblockdev, 20.04 has 2.23 and newest blivet needs at least 2.24. But there is no reason we shouldn't be able to run with older libblockdev, I'll prepare a fix for this. I'll move this issue to the blivet component as it isn't really a blivet-gui problem. Thank you for the report.
