### ISSUE TITLE
Crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by jayoh-dev** [storaged-project/blivet-gui#292]
Hello,

I installed blivet-gui on Ubuntu 20.04.3 from OBS using the commands:
```
echo 'deb http://download.opensuse.org/repositories/home:/vtrefny/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:vtrefny.list
curl -fsSL https://download.opensuse.org/repositories/home:vtrefny/xUbuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_vtrefny.gpg > /dev/null
sudo apt update
sudo apt install blivet-gui
```

But the blivet-gui crashes on starting with following logs:
```
Traceback (most recent call last):
  File "/usr/bin/blivet-gui", line 40, in <module>
    from blivetgui.dialogs.message_dialogs import ErrorDialog
  File "/usr/lib/python3/dist-packages/blivetgui/dialogs/message_dialogs.py", line 31, in <module>
    from .helpers import adjust_scrolled_size
  File "/usr/lib/python3/dist-packages/blivetgui/dialogs/helpers.py", line 34, in <module>
    from blivet import devicefactory
  File "/usr/lib/python3/dist-packages/blivet/devicefactory.py", line 27, in <module>
    from .devices import BTRFSDevice, DiskDevice
  File "/usr/lib/python3/dist-packages/blivet/devices/__init__.py", line 24, in <module>
    from .storage import StorageDevice
  File "/usr/lib/python3/dist-packages/blivet/devices/storage.py", line 33, in <module>
    from ..formats import get_format, DeviceFormat
  File "/usr/lib/python3/dist-packages/blivet/formats/__init__.py", line 46, in <module>
    from ..tasks import fsinfo
  File "/usr/lib/python3/dist-packages/blivet/tasks/fsinfo.py", line 29, in <module>
    from . import availability
  File "/usr/lib/python3/dist-packages/blivet/tasks/availability.py", line 377, in <module>
    technologies={blockdev.LVMTech.VDO: (blockdev.LVMTechMode.CREATE |
AttributeError: type object 'LVMTech' has no attribute 'VDO'
```

**Comment by vojtechtrefny** [comment]
This was already reported yesterday, I'll try to build a fixed version of blivet as soon as possible.

https://github.com/storaged-project/blivet/issues/982

**Comment by jayoh-dev** [comment]
I've been watching the issue you mentioned, could check working well. Thank you.
