### ISSUE TITLE
Not launching/opening

### ISSUE THREAD

**Issue by mrme02** [storaged-project/blivet-gui#368]
Running Debian Bullseye. X11 with Cinnamon desktop.

Upon launching, I get asked for my root password, nothing happens after that. Noob user, so unaware of what, if any logs are required to diagnose.

If any further detail is required, please let me know, so I can get this issue resolved.

**Comment by mrme02** [comment]
From console (su -)

I get the following (I tried this before, but gave up as they looked like the same error messages I get when running applications as root from the console)

Unable to init server: Could not connect: Connection refused

And,
(blivet-gui:144649): Gtk-CRITICAL **: 14:39:32.030: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault

**Comment by mrme02** [comment]
I just tried running this as my normal user after reinstalling `blivet-gui`, to see if I had missed anything. It asked for my password, then this is what was printed to the console,


> Traceback (most recent call last):
  File "/usr/bin/blivet-gui", line 117, in <module>
    main()
  File "/usr/bin/blivet-gui", line 110, in main
    client = BlivetGUIClient(server_socket=sockfile)
  File "/usr/lib/python3/dist-packages/blivetgui/communication/client.py", line 110, in __init__
    self.sock.connect(server_socket)
PermissionError: [Errno 13] Permission denied

**Comment by vojtechtrefny** [comment]
Sorry for late answer. I did a new release of blivet, there was a different issue reported on Debian (https://github.com/storaged-project/blivet/issues/1087) so it is possible that it fixes your problem too.

**Comment by mrme02** [comment]
I've updated to the latest version, but the issue still remains, same errors, and nothing logged. Just tried in a Bullseye VM, and confirms it runs without issue inside a VM, so the issue is with my Debian install. 

I'll reinstall Python, as that's where the issues seem to stem from.


Thank you for helping me out up to this point, I do appreciate your help :-)
