### ISSUE TITLE
blivet 3.11.0 + blivet-gui 2.5.0: `AttributeError: 'gi.repository.BlockDev' object has no attribute 'CryptoLUKSHWEncryptionType'`

### ISSUE THREAD

**Issue by CyberShadow** [storaged-project/blivet-gui#461]
Hi, not sure if the above combination of versions makes sense, but I noticed that e.g. [the Debian spec file allows any `blivet` version equal or above to 3.8.0](https://github.com/storaged-project/blivet-gui/blob/main/blivet-gui.spec#L33), and assuming `blivet` uses semantic versioning, perhaps this is an unexpected regression?

If I try to build and run blivet-gui 2.5.0 with blivet 3.11.0, I get this crash on startup:

```
Traceback (most recent call last):
  File "/nix/store/99sfw4pmwavsxfb8qymkvmjfcjv836b2-blivet-gui-2.5.0/bin/.blivet-gui-wrapped", line 39, in <module>
    from blivetgui.dialogs.message_dialogs import ErrorDialog
  File "/nix/store/99sfw4pmwavsxfb8qymkvmjfcjv836b2-blivet-gui-2.5.0/lib/python3.12/site-packages/blivetgui/dialogs/message_dialogs.py", line 31, in <module>
    from .helpers import adjust_scrolled_size
  File "/nix/store/99sfw4pmwavsxfb8qymkvmjfcjv836b2-blivet-gui-2.5.0/lib/python3.12/site-packages/blivetgui/dialogs/helpers.py", line 34, in <module>
    from blivet import devicefactory
  File "/nix/store/307wkiz321g5jkz2axgbidbz5lpxl8gy-python3.12-blivet-3.11.0/lib/python3.12/site-packages/blivet/devicefactory.py", line 25, in <module>
    from .devices import BTRFSDevice, DiskDevice
  File "/nix/store/307wkiz321g5jkz2axgbidbz5lpxl8gy-python3.12-blivet-3.11.0/lib/python3.12/site-packages/blivet/devices/__init__.py", line 24, in <module>
    from .storage import StorageDevice
  File "/nix/store/307wkiz321g5jkz2axgbidbz5lpxl8gy-python3.12-blivet-3.11.0/lib/python3.12/site-packages/blivet/devices/storage.py", line 33, in <module>
    from ..formats import get_format, DeviceFormat
  File "/nix/store/307wkiz321g5jkz2axgbidbz5lpxl8gy-python3.12-blivet-3.11.0/lib/python3.12/site-packages/blivet/formats/__init__.py", line 746, in <module>
    from . import biosboot, disklabel, dmraid, fslib, fs, luks, lvmpv, mdraid, multipath, prepboot, swap, stratis
  File "/nix/store/307wkiz321g5jkz2axgbidbz5lpxl8gy-python3.12-blivet-3.11.0/lib/python3.12/site-packages/blivet/formats/luks.py", line 36, in <module>
    from ..devicelibs import crypto
  File "/nix/store/307wkiz321g5jkz2axgbidbz5lpxl8gy-python3.12-blivet-3.11.0/lib/python3.12/site-packages/blivet/devicelibs/crypto.py", line 54, in <module>
    OPAL_TYPES = {"luks2-hw-opal": BlockDev.CryptoLUKSHWEncryptionType.OPAL_HW_AND_SW,
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/overrides/__init__.py", line 31, in __getattr__
    return getattr(self._introspection_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.BlockDev' object has no attribute 'CryptoLUKSHWEncryptionType'
```

I noticed this because blivet and blivet-gui are now in nixpkgs, and the nixpkgs auto-update bot [opened a PR to update the blivet package to 3.11.0](https://github.com/NixOS/nixpkgs/pull/354563). However, this PR seems to break blivet-gui due to the above.

**Comment by vojtechtrefny** [comment]
The problem is old version of libblockdev -- blivet 3.11 needs libblockdev 3.2.0.

**Comment by CyberShadow** [comment]
Ah, of course. Thank you!
